[Home](../../README.md)

### Model Evaluation

This is a demonstration of evaluating a model.

#### Step 1

Load the required dependencies.


In [1]:
# Step 1: Import frameworks
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score
import pickle


####  Step 2

Load the model for testing

In [2]:
filename = 'trained_model.pkl'
model_A = pickle.load(open(filename, 'rb'))


(Optional) Load a second model if you want to do comparative testing

In [3]:
filename = 'trained_model.pkl'
model_B = pickle.load(open(filename, 'rb'))

####  Step 3
Open and parse the test data CSV file and store the data as variable array data objects.

In [12]:
# Load test data (CSV)
testing_data = pd.read_csv('testing_data.csv')  # Load your test dataset

# Select the same features as the training data
X_test = testing_data[['Hand Strength', 'Max Rank Frequency', 'Unique Ranks', 'Unique Suits']]

# Select the action probabilities as the target
y_test = testing_data[['Fold', 'Check', 'Raise', 'Call', 'All-In']]  # These should be columns in your testing data

# Display first few rows of X_test and y_test to verify
print(X_test.head())
print(y_test.head())


   Hand Strength  Max Rank Frequency  Unique Ranks  Unique Suits
0              1                   2             4             4
1              1                   2             4             4
2              1                   2             4             4
3              1                   2             4             3
4              5                   1             5             3
       Fold     Check     Raise      Call    All-In
0  0.216917  0.531449  0.161621  0.065114  0.024899
1  0.183180  0.559048  0.145470  0.072898  0.039405
2  0.198399  0.649524  0.085941  0.054255  0.011881
3  0.201002  0.615434  0.101125  0.073376  0.009062
4  0.059576  0.120294  0.379411  0.341214  0.099505


#### Step 4



In [13]:
# Define features (same as during training)
features = ['Hand Strength', 'Unique Ranks', 'Unique Suits', 'Max Rank Frequency']

# Extract features from the testing data
X_test = testing_data[features]

# Verify the shape of the test data
print(f"Shape of X_test: {X_test.shape}")


Shape of X_test: (8381, 4)


#### Step 5



In [ ]:
# Use the model to make predictions on the test set
y_pred = model_A.predict(X_test)

# Display the predicted values
print(f"Predictions: {y_pred}")

Predictions: [[0.20736928 0.58083865 0.06232932 0.12445678 0.02500597]
 [0.20736928 0.58083865 0.06232932 0.12445678 0.02500597]
 [0.20736928 0.58083865 0.06232932 0.12445678 0.02500597]
 ...
 [0.20863112 0.58089183 0.06197562 0.12349105 0.02501038]
 [0.20757106 0.58093601 0.06235521 0.12424787 0.02488985]
 [0.20941128 0.57842921 0.06217562 0.12483251 0.02515138]]


#### Step 7

Manually calculate and evaluate the 'loss' and 'cost' of the model using the test data.

In [15]:
# Use model_A to predict on the test data
y_pred = model_A.predict(X_test)

# Now we'll prepare a table for easy display with actual, predicted, and loss
table = pd.DataFrame({
    X_test.columns[0]: X_test.iloc[:, 0],  # Display first feature for clarity
    X_test.columns[1]: X_test.iloc[:, 1],  # Display second feature, add more as needed
    'Actual': y_test,                      # Actual values from testing data
    'Predicted': y_pred.round(2),          # Predicted values rounded to 2 decimals
    'Loss': (y_test - y_pred).round(2)     # Loss between actual and predicted
})

# Display the table of actual, predicted, and loss
print(table)

# Calculate the cost (average loss)
cost = (y_test - y_pred).abs().mean()  # Taking absolute loss to avoid negative values
print(f"The cost (average loss) of this model is {cost:.4f}")

ValueError: Per-column arrays must each be 1-dimensional

You may want to do some manual predictions to understand your model.

In [ ]:
print(model_A.predict([[0.1]]))
print(model_A.predict([[1]]))

#### Step 8

Evaluate the X axis intercept and gradient or coefficient of your model by using the getter methods to return the intercept and coefficient from my_model() object.

In [ ]:
print(f'X Axis intercept: {model_A.intercept_}')
print(f'Coefficient: {model_A.coef_}')

#### Step 9. Multiple Variable Linear Regression

You should be able to understand the code snippets with less guidelines.

In [12]:
filename = 'my_saved_model_v2.sav'
model_C = pickle.load(open(filename, 'rb'))

In [13]:
# Optional
filename = 'my_saved_model_v2.sav'
model_D = pickle.load(open(filename, 'rb'))

In [18]:
mx_col = ['BMI','BP','FDR']
testing_data = pd.read_csv('2.4.1.testing_data.csv')
mx_test = np.array(testing_data[mx_col])
my_test = np.array(testing_data['Target'])

In [ ]:
my_pred = model_C.predict(mx_test)

# plot predictions and targets vs original features    
fig,ax=plt.subplots(1,len(mx_col),figsize=(12,3),sharey=True)
for i in range(len(ax)):
    ax[i].scatter(mx_test[:,i],my_test, label = 'target')
    ax[i].set_xlabel(mx_col[i])
    ax[i].scatter(mx_test[:,i],my_pred,color="orange", label = 'predict')
    ax[i].set_ylabel("Target"); ax[i].legend();
fig.suptitle("Diabetes Disease Progress")
plt.show()

In [ ]:
test_score = model_C.score(mx_test, my_test)
print(f'Training data score: {test_score}')

In [ ]:
print(model_C.predict([[0.1,0.1,0.1]]))
print(model_C.predict([[1,0.5,1]]))

In [ ]:
data = {col: mx_test[:, i] for i, col in enumerate(mx_col)}
data['Target'] = my_test
data['Predicted result'] = model_C.predict(mx_test)
data['Cost'] = my_test - model_C.predict(mx_test).round(2)

table = pd.DataFrame(data)
print(table)

In [ ]:
print(f'X Axis intercept: {model_C.intercept_}')
print(f'Coefficient: {model_C.coef_}')

#### Step 10

When your model is ready for operations, move it to the [3.Operations\3.1.Deploy_Model](\3.Operations\3.1.Deploy_Model) folder.